// app/layout.tsx
import type { Metadata } from "next";
// app/layout.tsx
import { Inter } from 'next/font/google'
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Navbar } from "@/components/Navbar";
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['200', '300', '400', '500'], // Added lighter weights
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased font-light"> {/* Changed to font-light */}
        <UserProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="flex-1 flex flex-col min-w-0">
              <Navbar />
              <main className="flex-1 overflow-y-auto bg-[#F8F9FA] p-6">
                {children}
              </main>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}